name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          GHCR_BOT_TOKEN: ${{ secrets.GHCR_BOT_TOKEN }}
        run: echo $GHCR_BOT_TOKEN | docker login ghcr.io -u zakodium-bot --password-stdin
      - name: Build and push the Docker image
        run: |
          docker build . -t ghcr.io/zakodium/label-print-server:${GITHUB_REF##*/}
          docker push ghcr.io/zakodium/label-print-server:${GITHUB_REF##*/}
